services:
  pia-scrap:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - path: .env
        required: false
    volumes:
      - ./output:/app/output
    environment:
      - OUTPUT_RETENTION_DAYS=30
    restart: unless-stopped
